name 'ghoneycutt-localization'
version '1.0.0'
source 'git://github.com/ghoneycutt/puppet-module-localization.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'put a summary here'
description 'put a description here'
project_page 'https://github.com/ghoneycutt/puppet-module-localization'

dependency 'puppetlabs/stdlib', '>=3.2.0'
